### ISSUE TITLE
plugin not working

### ISSUE THREAD

**Issue by oveeM** [ThisisCanada98/DragonballFusionsNTR#6]
running cfw with newest updates to luma and ntr selector<3.6>, playing a digital copy of the game. After loading ntr, when I open the game I don't get the green screen to verify the plugin is running, and nothing happens when I press select to go to the cheat menu. I've tried this with all versions 3.0, 4.0, and 4.1 of your plugin.

**Comment by oveeM** [comment]
also, on an old 3ds running 11.5.

**Comment by HeroMines** [comment]
change the name to cheat.plg

**Comment by oveeM** [comment]
Did that, however after getting it to open(finally), none of the codes
actually work. Everything is on its newest version. Any ideas why the codes
don't actually do anything?

**Comment by ThisisCanada98** [comment]
Cheats are working on my end just fine. I will be releasing a beta version today, so maybe wait for that and than report back after testing some codes out.

**Comment by oveeM** [comment]
Sounds like a plan. Thanks for getting back to me

**Comment by ThisisCanada98** [comment]
https://github.com/ThisisCanada98/DragonballFusionsNTR/releases/tag/BETA.4.2

**Comment by oveeM** [comment]
currently trying it, and I don't know if I'm missing something, but when I activate the codes in the menu, they never actually do anything. they say on, then I exit the menu and nothing changes.

**Comment by ThisisCanada98** [comment]
Are you using the uncensored version of the game?

**Comment by oveeM** [comment]
Yes I am primarily, however I've tried it on both with the 4.0 and 4.1 releases and had the same issue

**Comment by ThisisCanada98** [comment]
Well thats the problem the uncensored version differs, slighlty, but still enough for codes to  not work.

**Comment by oveeM** [comment]
Got it. Thank you for that. Just curious, any chance you'll do a version for the uncensored version?

**Comment by ThisisCanada98** [comment]
Its possible if I get around to it,The problem is that the Cencosored and Uncensored version have the same title ID so I can not have both at the same time installed.

**Comment by oveeM** [comment]
Makes sense. And I'd be very excited to see a version for the uncensored game. So if I would modify the game on the normal version with the plugin, could it be transferred back to the uncensored game?

**Comment by ThisisCanada98** [comment]
yes

**Comment by oveeM** [comment]
would this be as simple as launching the game with your plugin, selecting my codes, saving, and then opening the uncensored game?

**Comment by ThisisCanada98** [comment]
Depends on how you do It, Best way would be to get the EU version of the game. You could than use FBI to transfer you saves back and forth. You would use the EU version for its plugin and than transfer the save back over.

**Comment by oveeM** [comment]
alright, thank you!

**Comment by oveeM** [comment]
so, after a lot of trial and error, I've found that on both the US and EUR versions of your plugin that the only codes that worked, at least for me, were the cac face, all characters, other characters to level 1, and ss4 upper body. the cac moves were not working, nor were the hair, dragon balls, or character swap.
